<?php

/**
 * @file
 * Administrator is able to see all loggedin users on the website.
 */

/**
 * Implements hook_menu().
 */
function loggedin_users_list_menu() {
  $items = array();
  $items['admin/config/people/loggedin_users_list'] = array(
    'title' => 'Logged-in users list',
    'description' => 'List of loggedin user at this time.',
    'access arguments' => array('administer'),
    'page callback' => 'loggedin_users_list_page',
    'file' => 'loggedin_users_list.admin.inc',
  );

  $items['admin/config/people/loggedin_users_list/logout/%'] = array(
    'title' => 'Log out User',
    'description' => 'Logout user from his machine.',
    'access arguments' => array('administer'),
    'page arguments' => array(5),
    'page callback' => 'logout_user_custom_page',
    'file' => 'loggedin_users_list.admin.inc',
  );

  return $items;
}

/**
 * Custom theme function to show results.
 */
function loggedin_users_list_theme() {
  $themes = array(
    'loggedin_users_list' => array(
      'variables' => array('users_no' => NULL, 'userdata' => NULL),
      'template' => 'loggedin-users-list',
    ),
  );
  return $themes;
}
